// One unique image per product.
// Images are generated by zudyog-ingest/generate_images.py (DALL-E 3).
// Run: cd zudyog-ingest && python generate_images.py
export function getProductImage(id: string, _category: string): string {
  return `/products/${id}.jpg`;
}
